--- # Project - install git ##### Steps - Check if folder is present, copy tar, untar, delete tar, list folder,

- hosts: awshosts
  become: yes

  tasks: 
  - name: Check if the proper git version exists
    stat:
      path: /var/git-2.6.4/bin/git
    register: git

    
  - debug: msg="{{git.stat.exists}}"

  - name: Stop if git i already on host
    fail: msg="Git is already installed"
    when: git.stat.exists == true

  - name: Copy file with specific and permissions
    ansible.builtin.copy:
      src: /home/ec2-user/git.tar
      dest: /var
      owner: root
      group: root
      mode: '0644'

  - name: Check for cp success
    shell:
            "ls -l /var/git.tar"
    register: lscmd
    tags: lscmd

  - debug: msg="{{lscmd.stdout}}"

  - name: Unarchive the Git
    ansible.builtin.unarchive:
      src: /var/git.tar
      dest: /var/
      remote_src: yes

  - name: Remove the archive
    ansible.builtin.file:
      path: /var/git.tar
      state: absent

  - name: Check if git-2.6.4 is present
    shell:
            "ls -l /var/git-2.6.4/bin/git"
    register: lscmd2
    tags: lscmd2

  - debug: msg="{{lscmd2.stdout}}"